name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 2.2.4
authors:
  - Jimmy Aumard <jimmy.aumard@gmail.com>
  - Rushio Consulting <dev@rushio-consulting.fr>
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://rushio-consulting.fr

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_ml_vision: ^0.9.3
  flutter_widgets: ^0.1.6
  path_provider: ^1.4.0
  pedantic: ^1.8.0+1
  device_info: ^0.4.1+1
  camera: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
